### ISSUE TITLE
Unresolved reference: util

### ISSUE THREAD

**Issue by yamayel** [mohammednawas8/EasyFood#1]
At MealBottomDialog.kt it gives an Unresolved reference error: util in the following lines:

import com.example.easyfood.util.Constants.Companion.CATEGORY_NAME
import com.example.easyfood.util.Constants.Companion.MEAL_AREA
import com.example.easyfood.util.Constants.Companion.MEAL_ID
import com.example.easyfood.util.Constants.Companion.MEAL_NAME
import com.example.easyfood.util.Constants.Companion.MEAL_STR
import com.example.easyfood.util.Constants.Companion.MEAL_THUMB

**Comment by umesh8412** [comment]
not just in MealBottomDialog.kt in this file but  in Activity files that error is showing  same error Unresolved reference: utilUnresolved reference: util

**Comment by umesh8412** [comment]
hii @mohammednawas8  i have fix the above error can u review at the commit

**Comment by mohammednawas8** [comment]
Hey @umesh8412, thanks for your time
I noticed that you moved the Constants to the HomeFragment which is not good practice. You can keep them in the `Constants` class but you can update the gradle files and other files that could solve the issue.

**Comment by umesh8412** [comment]
I have run the code it worked also the chages are done by seeing ur easy food tutorial, and error are cause by that companion object and the file format i. e. Util is not exist in that app

**Comment by mohammednawas8** [comment]
Please note that this repository is different from the one on youtube. its not the exact same code and that is why you found differences in the code. However after i looked at my youtube video to remember how i did it in there im going to merge this.

Thanks for contributing
